apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: koa-api-test
  name: koa-api-test-rc
spec:
  replicas: 1
  selector:
    app: koa-api-test
    role: replicas
  template:
    metadata:
      labels:
        app: koa-api-test
        role: replicas
    spec:
      restartPolicy: Always
      containers:
      - image: quyennt/koa-api-test-onbuild
        name: koa-api-test
        ports:
        - containerPort: 4000
          name: app-port
        env:
        - name: RETHINKDB_HOST
          value: rethinkdb-driver
